### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by qhy040404**
**Description:**
Fix typo

**Related issue:**
None

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Review by marko-zivic-93 — APPROVED** [review]

**Comment by qhy040404** [comment]
I don't know why dist/index.js generated in CI is 4142kB, but on my own computer it is 4144kB.

**Comment by dmitry-shibanov** [comment]
> I don't know why dist/index.js generated in CI is 4142kB, but on my own computer it is 4144kB. Maybe node.js version is different. I have node.js 17 on my computer,

Hello @qhy040404. For setup-java we use the same major version as in action.yml (node16)

**Comment by qhy040404** [comment]
> Hello @qhy040404. For setup-java we use the same major version as in action.yml (node16)

Thanks for your reply. I just download dist file from CI, and commit them as output dist.

**Review by dmitry-shibanov — APPROVED** [review]

**Comment by dmitry-shibanov** [comment]
@qhy040404 Thank you for your contribution.

**Pull request merged**
