### PR TITLE
Add Amazon Corretto distribution

### LINKED ISSUE #68: Add support for Amazon Corretto binaries
With work being done towards adding additional binary distributions of OpenJDK as options (likely under the "distro" option, see e.g. https://github.com/actions/setup-java/pull/67), it would be useful to include Amazon Corretto among the distro options.

### PR DESCRIPTION
**Pull request by WtfJoke**
**Description:**
Add feature to allow setup-java to run with major versions of available amazon correttos binaries.
The available (major) versions are fetched from https://corretto.github.io/corretto-downloads/ (from the following json: https://corretto.github.io/corretto-downloads/latest_links/indexmap_with_checksum.json).

I've tested it also with a random java project here: [Workflow-run](https://github.com/WtfJoke/quarkus-workshops/runs/5805055768?check_suite_focus=true)
**Related issue:**
Fixes #68 

**Check list:**
- [x] Mark if documentation changes are required.
- [x] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Comment by dmitry-shibanov** [comment]
Hello @WtfJoke. Thank you for your pull request. I have some questions: 
 - Do Amazon Corretto binaries have unstable versions ?
 - Do Amazon Corretto binaries have `jre` versions

**Comment by WtfJoke** [comment]
Hi @dmitry-shibanov 

I'll try to answer the questions :)
> * Do Amazon Corretto binaries have unstable versions ?

Not that I know of (at least the json, doesnt provide anything and I didnt found anything else documented).


> * Do Amazon Corretto binaries have `jre` versions

Not many, but they do (for example they provide [jre 8 for windows](https://corretto.aws/downloads/resources/8.322.06.1/amazon-corretto-8.322.06.1-windows-x86-jre.zip))

Is there a particular reason for your question?

**Comment by dmitry-shibanov** [comment]
Hello @WtfJoke. Thank you for your responses. Could you please add support for jre versions ?

**Comment by WtfJoke** [comment]
Hi @dmitry-shibanov 

jre versions are already supported, see this test case for example:
https://github.com/actions/setup-java/blob/411c86b2a444b35c7a9c70c8cb2ef87160456c33/__tests__/distributors/corretto-installer.test.ts#L54

Or did I missunderstand you?

**Comment by dmitry-shibanov** [comment]
Thank you @WtfJoke. Could you please include this test case to e2e ?

**Comment by WtfJoke** [comment]
Sure I've included it in the e2e-versions workflow (they provide only jre releases currently for windows in version 8).

As a small bonus 🎈  I've also changed the version of job `setup-java-custom-package-type` to java version 17 (instead of 16), so temurin doesnt need to be excluded anymore as they provide JRE releases for LTS versions :)

**Comment by dmitry-shibanov** [comment]
Thank you.

**Comment by btsteve** [comment]
Is there a way to test the unreleased version?

**Comment by WtfJoke** [comment]
@btsteve 
Yes there is, you can use my fork + branch in your worfklow like this:

```yaml
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install JDK 11
        uses: WtfJoke/setup-java@addCorretto
        with:
          distribution: corretto
          java-version: 11
```

Or here the [full workflow yaml](https://github.com/WtfJoke/quarkus-workshops/actions/runs/2084847059/workflow)

**Comment by WtfJoke** [comment]
Hey @dmitry-shibanov 
Just rebased the commits to the latest main and resolved the conflicts.
Is there some kind of ETA when you review/merge this PR?

Thanks a bunch!

**Comment by mu88** [comment]
@WtfJoke: can I also install Corretto on a Windows agent (`runs-on: windows-latest`)? If so, can I somehow already test your changes in one of my GitHub Actions? Or do I need to wait until it is released?

**Comment by WtfJoke** [comment]
> @WtfJoke: can I also install Corretto on a Windows agent (`runs-on: windows-latest`)? If so, can I somehow already test your changes in one of my GitHub Actions? Or do I need to wait until it is released?

Yes, its also possible in windows. 
You can already test it by using `WtfJoke/setup-java@addCorretto` instead of `actions/setup-java@v3`

See the example (there is also a full workflow yaml linked) in the comment above (you just can replace ubuntu with windows as you've already have written):

https://github.com/actions/setup-java/pull/312#issuecomment-1087855089

If you still need help, feel free to post your workflow.

**Comment by TomBeckett** [comment]
For what its worth I've been using @WtfJoke's fork for a while now and seems to be working great!

@dmitry-shibanov Is this good to merge? Is there anything in particular I should test?

**Comment by dmitry-shibanov** [comment]
Hello @WtfJoke. Could you please sync with the main ? I've tested your changes and it works as expected.

**Comment by WtfJoke** [comment]
Hi @dmitry-shibanov 
I've rebased my branch with the latest main and fixed the conflicts. Great that you were able to test it.

Looking forward for the merge 😄 🚀

**Comment by aaiezza** [comment]
Great work!

Does anyone have an example of how to use this now?

**Comment by spaletta** [comment]
@aaiezza See https://github.com/actions/setup-java#usage

**Pull request merged**
