### PR TITLE
Revert "Add support for Oracle JDK"

### PR DESCRIPTION
**Pull request by dmitry-shibanov**
Reverts actions/setup-java#401

### CODE REVIEW

**Comment by fniephaus** [comment]
What's the reason for reverting #401?

**Comment by brcrista** [comment]
@fniephaus unfortunately, we're not able to support Oracle JDK in `setup-java`.  I'm sorry for the confusion.  We should have caught it sooner on the PR and relevant issue.

**Review by brcrista — APPROVED** [review]

**Comment by brcrista** [comment]
If you'd like to send me an email at brcrista at github.com, I'd be happy to discuss the blockers with you in more detail.

**Comment by carimura** [comment]
@brcrista @fniephaus i'd like to join this conversation. Will follow up by email.

**Comment by dmitry-shibanov** [comment]
Hello @Gakk. Thank you for your report. We've released a new version [v3.8.0](https://github.com/actions/setup-java/releases/tag/v3.8.0). The major tag will be updated later.

**Comment by Gakk** [comment]
> We've released a new version [v3.8.0](https://github.com/actions/setup-java/releases/tag/v3.8.0)

Thank you for responding so quickly 🚀
After a friendly nudge Dependabot produced a PR bumping to 3.8.0, and all checks passed 👍

**Comment by ruffy085** [comment]
#421

**Comment by ruffy085** [comment]
@AlenaSviridenko

**Pull request merged**
