### PR TITLE
feat: add support for SapMachine JDK/JRE

### LINKED ISSUE #72: Add support for SapMachine binaries
With work being done towards adding additional binary distributions of OpenJDK as options (likely under the "distro" option, see e.g. #67), it would be useful to include the SapMachine binaries among the distro options

### PR DESCRIPTION
**Pull request by Shegox**
**Description:**
This PR adds support for setting up the [SapMachine](https://github.com/SAP/SapMachine) JDK/JRE using the setup-java action. 
The implementation is heavily inspired by the [dragonwell implementation](https://github.com/actions/setup-java/tree/main/src/distributions/dragonwell).
The setup-java supports setting up SapMachine for JRE and JDK for following operating systems/architectures: 
- macos (arm/x86)
- linux (arm/x86)
- linux-muse (x86) (for alpine containers)
- windows (x86)

The releases URL `https://sap.github.io/SapMachine/assets/data/sapmachine-releases-all.json`, which is used to determine the download URL, contains the up-to-date full list of all SapMachine JDKs and JREs.

Otherwise this PR adds `21` to the list of major e2e tested versions for all releases, which works for all. If you want I can as well add it to a separate PR.

**Related issue:**
fixes #72 
fixes https://github.com/SAP/SapMachine/issues/821

**Check list:**
- [x] Mark if documentation changes are required.
- [x] Mark if tests were added or updated to cover the changes.

Tested additionally via: 
- e2e tests: https://github.com/Shegox/setup-java/actions/runs/8452912940
- SapMachine specific e2e setup tests: https://github.com/Shegox/setup-sapmachine-test/actions/workflows/matrix.yml

### CODE REVIEW

**Review by RealCLanger — APPROVED** [review]
Great stuff. Thank you for doing this.

**Review by gdams — APPROVED** [review]
LGTM

**Comment by gdams** [comment]
@aparnajyothi-y can we get a review of this PR please

**Comment by joergmann** [comment]
great!

**Comment by rjayasinghe** [comment]
Great! Go for it! 💚

**Comment by RealCLanger** [comment]
@HarithaVattikuti can you take a look?

**Comment by RealCLanger** [comment]
@priyagupta108 can you take a look?

**Comment by RealCLanger** [comment]
@mahabaleshwars Could you take a look here or give us some ETA for when this can be merged? We have quite some folks waiting for this... Thanks

**Comment by fniephaus** [comment]
@RealCLanger https://github.com/actions/setup-java/pull/501 is stuck in a similar fashion: no response from the maintainers for months. I was told they need their lawyers to review the license of the JDK distro to ensure the distro can be integrated into this action. We went through this with them when adding Oracle JDK (https://github.com/actions/setup-java/pull/401), but somehow it now seems that process is stuck indefinitely.

**Comment by RealCLanger** [comment]
@stoe Could you find out something about the progress of this already?

**Comment by aparnajyothi-y** [comment]
Hello Everyone, We have prioritized the [feature request](https://github.com/actions/setup-java/issues/72) for this Q4 to implement support for SapMachine JDK/JRE. We have started reviewing and testing [this PR](https://github.com/actions/setup-java/pull/614) for the feature request. We will update you once we have some feedback.

**Comment by RealCLanger** [comment]
> Hello Everyone, We have prioritized the [feature request](https://github.com/actions/setup-java/issues/72) for this Q4 to implement support for SapMachine JDK/JRE. We have started reviewing and testing [this PR](https://github.com/actions/setup-java/pull/614) for the feature request. We will update you once we have some feedback.

Thanks for the update. So let's hope this can be integrated by Q4 or even sooner... 😄

**Comment by skateball** [comment]
> Hello Everyone, We have prioritized the [feature request](https://github.com/actions/setup-java/issues/72) to implement support for SapMachine JDK/JRE. We have started reviewing and testing [this PR](https://github.com/actions/setup-java/pull/614). We will update you once we have some feedback.

@aparnajyothi-y Hi, can you please give an update how long this will take?
Can we help/assist you in any way to get this PR sooner solved?
Best Regards Christian

**Comment by RealCLanger** [comment]
Any updates (@aparnajyothi-y) ?

**Comment by aparnajyothi-y** [comment]
Hello Everyone, we are in the process of reviewing this PR. We will update once the review completed.

**Review by priyagupta108 — APPROVED** [review]

**Review by aparnajyothi-y — APPROVED** [review]

**Review by SkakimSAP — APPROVED** [review]

**Review by skateball — APPROVED** [review]
LGTM. How long does it take that I know when to organize cake?

**Review by HarithaVattikuti — APPROVED** [review]

**Pull request merged**
