### PR TITLE
Improve error handling for restore caching

### PR DESCRIPTION
**Pull request by dmitry-shibanov**
**Description:**
In scope of this pull request we add error handling to throw error only for ValidationError.

**Related issue:** https://github.com/actions/setup-java/issues/295

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Review by ChrisCarini — APPROVED** [review]

**Comment by Pompo17102** [comment]
Deposit through the bitcoin wallet for any help 
     bc1q5v34g2dym8c7x5mpfp7wdqp5hse38p99p4dggx

**Review by brcrista — APPROVED** [review]
I agree with the change, but how does it relate to https://github.com/actions/setup-java/issues/295?

**Comment by brcrista** [comment]
@actions/actions-cache, do you have any feedback?  For context, the `setup-` actions use the `@actions/cache` package to cache dependencies directly, which lets you omit `actions/cache` as a separate step.

**Comment by dmitry-shibanov** [comment]
Hello @brcrista. Actually, as I checked the issue reproduces with node 16 only. On the previous action version it works as expected. I think it's related itself to the change of the default node version and buffer size. I could reproduce the same behaviour with action/cache when I removed [this error handling logic](https://github.com/actions/cache/blob/main/src/restore.ts#L59-L64) and archive size was more than 2147483647.
 - https://github.com/actions/toolkit/blob/39b96406423e444b058d2602e2cea8f889342ee4/packages/cache/src/internal/downloadUtils.ts#L113-L115

**Comment by aparna-ravindra** [comment]
might this be related to https://github.com/actions/toolkit/pull/1030 ?

**Comment by dmitry-shibanov** [comment]
Thank you @aparna-ravindra. It works. I've updated the pull request.

**Comment by dmitry-shibanov** [comment]
I'm going to close the pull request because the issue was resolved in scope of this pull request https://github.com/actions/setup-java/pull/308

**Pull request closed without merging**
