### PR TITLE
Update actions/cache to 3.0.4 version

### PR DESCRIPTION
**Pull request by kotewar**
**Description:**
Updated `actions/cache` to [latest](https://github.com/actions/toolkit/blob/main/packages/cache/package.json#L3) version 3.0.4

**Related issue:**
Some [bug fixes](https://github.com/actions/toolkit/blob/main/packages/cache/RELEASES.md#304) were made in the actions/cache module that are needed to be made available to the `setup-java` action users to utilise all the `actions/cache` feature.

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Comment by dmitry-shibanov** [comment]
Hello @kotewar. Thank you for your pull request. The actions/cache 3.0.5 is available. Could you please update it to the 3.0.5 version ? Besides, could you please revert changes regarding to other dependencies ?

**Comment by kotewar** [comment]
Hi @dmitry-shibanov, `actions/cache` 3.0.5 currently has one [issue](https://github.com/actions/cache/issues/957) that's being figured out, hence kept it `v3.0.4`. I'll upgrade it to `3.0.5` as soon as we have a confirmation that issue. Meanwhile let's keep this PR on hold.

Secondly, the changes to other dependencies occurred as part of the checks where the `package-lock.json` had to be in sync with the `package.json` changes, and the corresponding licenses had to be updated to pass the checks. In case I am doing it wrong, please suggest me on how it can be done correctly. 

Also, I suspect some of the dependencies upgraded could be a result of updated dependencies of `actions/cache` newer versions as it internally refers to `actions/core` and [some other dependencies.](https://github.com/actions/toolkit/blob/main/packages/cache/package.json#L40)

**Comment by dmitry-shibanov** [comment]
Thank you for your clarification. Could you please sync with main and run `npm install --save @actions/cache@3.0.4` or `npm update @actions/cache@3.0.4` commands because I've got the minimal update of package-lock.json. Besides, the `actions/core` is already to the latest version on main.

**Comment by kotewar** [comment]
I can try that. 

I actually updated the version of `actions/cache` package.json manually and ran `npm install`, and doing so updated the `package-lock.json` completely it seems.

**Comment by kotewar** [comment]
I've made the necessary changes, let me know if it looks good to you (after the checks are all passed). 
Let's also keep this PR on hold till we have a confirmation if we're good to upgrade it to 3.0.5.

**Review by dmitry-shibanov — APPROVED** [review]

**Comment by dmitry-shibanov** [comment]
It looks good. Thank you!

**Review by marko-zivic-93 — APPROVED** [review]

**Review by naveedsandhu34 — APPROVED** [review]

**Pull request merged**
