### PR TITLE
Set output `cache-hit` to indicate if cache was hit

### PR DESCRIPTION
**Pull request by schuenadel**
**Description:**
Add the `cache-hit` output to be able to execute later steps depending on if the cache was hit like it is possible with [actions/cache](https://github.com/actions/cache). Like described here: https://github.com/actions/cache/tree/main#Skipping-steps-based-on-cache-hit

**Related issue:**
~None~
Edit: Later this issue came up, which is addressed here: https://github.com/actions/setup-java/issues/306

**Check list:**
- [x] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Comment by dmitry-shibanov** [comment]
Hello @schuenadel. Thank you for your pull request. Could you please add check that matchedKey and primaryKey are equal, because for now the cache can hit for the restore key.

**Comment by schuenadel** [comment]
> Could you please add check that matchedKey and primaryKey are equal, because for now the cache can hit for the restore key.

Thanks, that makes sense. I misunderstood the return value of `restoreCache` to only return on a "real" cache hit. Fixed that in https://github.com/actions/setup-java/pull/275/commits/edfea5c367da9d10a274d4508ceba5c76e640bac

**Review by dmitry-shibanov — APPROVED** [review]

**Review by vsafonkin — APPROVED** [review]

**Comment by schuenadel** [comment]
@dmitry-shibanov Is there anything else needed to get this merged? Asking because I don't have the rights to merge.

**Comment by dmitry-shibanov** [comment]
Hello @schuenadel. Sorry for the late response. Could you please sync with the main branch ?

**Pull request merged**
