### PR TITLE
GraalVM support

### PR DESCRIPTION
**Pull request by zharinov**
**Description:**
- New installer fetches GraalVM CE releases from the GitHub API
- JDK versions can be specified using short (`17`), long (`17.0.1`) or fully-qualified form (`17.0.2+22.0.0.2`)
- It matches required JDK version against hard-coded GraalVM mapping
  - `JDK ↔ GraalVM` mapping isn't that easy to obtain, so I've created [GitHub action](https://github.com/zharinov/graalvm-version-mapping) that downloads each release, runs `java -version` and prints collected data.
  - I know that maintaining hard-coded map of versions is the serious limitation, but this allows to specify JDK version like any other installer does.
- This implementation cares more about JDK side and testing matrix usage. For `native-image` and other graal-specific features, [official GitHub action](https://github.com/graalvm/setup-graalvm) should be considered instead.

**Related issue:**
- Closes: #195

**Check list:**
- [x] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Comment by zharinov** [comment]
Hi folks, I hope to receive some feedback and iterate on this until it can be marked ready for review.

**Comment by sebthom** [comment]
@zharinov any specific reason why you withdraw your PR?

**Comment by zharinov** [comment]
https://github.com/graalvm/setup-graalvm

**Comment by sebthom** [comment]
unfortunately that doesn't really cut it. I am interested in matrix builds (for Java compilation and tests) against different jdk vendors, not into native image builds. and for this use case it would be extremely helpful if setup-java would allow the installation of graalvm.

**Comment by zharinov** [comment]
Okay, I see. I probably would like to re-open and finish it, if someone of `setup-java` contributors is interested to review my code and release it.

**Pull request closed without merging**
