### PR TITLE
Add support for maven/gradle versions

### LINKED ISSUE #40: Allow to customize Maven version
It should be possible to set a specific Maven version to use with `mvn`. For that it should be optionally possible to download also Maven from some Apache mirror (https://maven.apache.org/download.cgi) after downloading Java and then use that mvn version.

### PR DESCRIPTION
**Pull request by jvalkeal**
- Essentially use same concepts as jdk install to switch
  maven and gradle versions if those are defined with config.
- Bump to tool-cache 1.3.0 as 1.0.0 tries to use
  node_modules/@actions/tool-cache/scripts/externals/unzip which doesn't have
  execute flag so you'd get `Permission denied`
- `extractZipNix` in toolkit no longer support relative path so needs to
  resolve absolute path before passing file to these methods.
- Commit has my local build for `index.js` which probably should get
  recreated but makes it easier to test this from a PR branch.
- Fixes #40

For example this:
```
    - name: Set up JDK 1.8
      uses: jvalkeal/setup-java@gh40
      with:
        java-version: 1.8
        maven-version: 3.6.1
        gradle-version: 5.6.2

    - name: maven home
      run: echo $M2_HOME

    - name: maven version
      run: mvn -v

    - name: gradle home
      run: echo $GRADLE_HOME

    - name: gradle version
      run: gradle -v
```

Will output something like:
```
2020-01-17T13:00:16.5204913Z /opt/hostedtoolcache/maven/3.6.1/x64
...
2020-01-17T13:00:17.2252202Z Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T19:00:29Z)
...
2020-01-17T13:00:17.2965824Z /opt/hostedtoolcache/gradle/5.6.2/x64
...
2020-01-17T13:00:17.8507839Z Welcome to Gradle 5.6.2!
2020-01-17T13:00:17.8507925Z 
2020-01-17T13:00:17.8508036Z Here are the highlights of this release:
2020-01-17T13:00:17.8511449Z  - Incremental Groovy compilation
2020-01-17T13:00:17.8520303Z  - Groovy compile avoidance
2020-01-17T13:00:17.8520773Z  - Test fixtures for Java projects
2020-01-17T13:00:17.8521043Z  - Manage plugin versions via settings script
2020-01-17T13:00:17.8521091Z 
2020-01-17T13:00:17.8521370Z For more details see https://docs.gradle.org/5.6.2/release-notes.html
2020-01-17T13:00:17.8521457Z 
2020-01-17T13:00:17.8521499Z 
2020-01-17T13:00:17.8521724Z ------------------------------------------------------------
2020-01-17T13:00:17.8521821Z Gradle 5.6.2
2020-01-17T13:00:17.8522042Z ------------------------------------------------------------
...
```

### CODE REVIEW

**Comment by martinpaljak** [comment]
Would be nice to have this! Maybe the PR has better chance if it is rebased to current master?

**Comment by joschi** [comment]
@jvalkeal Why not use the [Gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) or [Maven wrapper](https://github.com/takari/maven-wrapper) instead?

That way you can build the project locally and aren't depending on the GitHub action to set up everything for you.

**Comment by jvalkeal** [comment]
@joschi I do use wrappers but this was just a way to pick maven/gradle versions if you don't use wrappers.

**Comment by joschi** [comment]
@jvalkeal I'm afraid that this would lead to feature creep in this GitHub action.

Why stop at Gradle and Maven, why not add SBT, Leiningen, Buildr, Ivy, and Bazel, too? And these are just the build systems shown at https://search.maven.org/. 😉

There are dedicated GitHub actions for setting up [Gradle](https://github.com/marketplace/actions/gradle-command) and [Maven](https://github.com/marketplace/actions/setup-maven), so I wonder if it makes sense to include it in `setup-java`.

**Comment by brunoborges** [comment]
I agree this proposal goes way beyond the objective of this action and should be dropped, given all that has been said already.

**Comment by kwin** [comment]
Then you should get rid of all Maven artifacts in setup-java. Currently it already sets up the server.xml in https://github.com/actions/setup-java/blob/4003c04fbcd7c6d5d67fa11e57d706021663f6b2/src/auth.ts#L44. But I agree that probably separating set up of Java and Build System makes sense.

**Comment by joschi** [comment]
@kwin Not disagreeing with you here. In my humble opinion this kind of functionality should live in the respective GitHub actions for Maven and Gradle.

Neither @brunoborges nor I are contributors to or maintainers of this GitHub action, so we can only offer our input. 😉

**Comment by stCarolas** [comment]
@joshmgross @clarkbw @konradpabjan What do you think about discussion above and issue https://github.com/actions/setup-java/issues/60 ?

**Comment by clarkbw** [comment]
I've seen this question come up several times for different actions. And we should likely clarify the contribution guidelines for this action so it is clear.  We are not interested in supporting all clients.  These actions exist as the best way to get ~80% of customers up and running quickly.  This means good defaults and we support the majority clients / configurations.  Supporting all configurations and clients would make this too complicated to maintain and use.

For setup-java I think that means we support maven and gradle out of the box as these are very common client configurations.  Of course we won't support all of the maven or gradle features and so we should direct people to those more complete actions for their areas.  Similar for Ivy and anything else we should likely link out to known good actions.  Its going to be hard to know if this feature of maven or gradle is required to be supported so it might be a judgement call sometimes.

**Comment by dmitry-shibanov** [comment]
Hello everyone. I'm closing this pull request, because we don't have plans to add support for maven or gradle to setup-java, as it was discussed in https://github.com/actions/setup-java/issues/40.

**Pull request closed without merging**
