### PR TITLE
Add versions properties to cache

### PR DESCRIPTION
**Pull request by Endi327**
**Description:**
When using [refreshVersions](https://github.com/jmfayard/refreshVersions) plugin, all the versions are managed in one particular file called **versions.properties**. This file is created by the plugin in the root directory and only used for handling versions in one place. As you can see they have quite a huge user base, so this would help a lot of users. 

This PR adds the files` **/versions.properties` to the cache key calculation (in addition to the existing **/*.gradle*, **/gradle-wrapper.properties).

**Related issue:**
None.

**Check list:**
- [x] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Comment by dmitry-shibanov** [comment]
Hello @Endi327. Thank you for your pull request. I think it looks good, just some minor questions. 
 - Does the pull request related to https://github.com/actions/setup-java/issues/237 ?
 - Do you know how often file is changed ? 
 - If it's possible, could you please attach public repository for testing purposes.

**Comment by Endi327** [comment]
Hello @dmitry-shibanov. Thank you for you reply. Let me answer your questions:

- Does the pull request related to Include version catalog file in filehash in the Gradle cache key #237 ? -> The basic idea is the same, we would like to handle all versions in one specific file. However, #237 is about using version catalog and my PR is about using refreshVersions plugin or handling all dependency version in `versions.properties` file.
- Do you know how often file is changed ? -> It will change every time we add a new dependency or looking for updates and run `./gradlew refreshVersions`. 
- If it's possible, could you please attach public repository for testing purposes. -> Yes, I have a public repository: https://github.com/Endi327/fortnightly/tree/feature/refreshVersions. I already configured the refreshVersion plugin and to use my forked version of actions/setup-java.

**Comment by dmitry-shibanov** [comment]
Hello @Endi327. Thank you for you response. About the second question I'm just curious about it because I do not want to cause constant saving of the cache. It'll lead to the longer builds. How often will the `./gradlew refreshVersions` command be used ?
I'll test with your changes. For now I'll start up checks on the CI. 
Thank you!

**Comment by dmitry-shibanov** [comment]
Could you please run the `npm run format` command.

**Comment by Endi327** [comment]
@dmitry-shibanov Updated the unit tests so now all checks have passed.

**Comment by Endi327** [comment]
@dmitry-shibanov Is there any update on this?

**Review by dsame — APPROVED** [review]

**Comment by dmitry-shibanov** [comment]
Hello @Endi327. Sorry for the late response. Could you please sync with the main branch ?

**Review by IvanZosimov — APPROVED** [review]

**Review by dsame — APPROVED** [review]

**Review by dmitry-shibanov — APPROVED** [review]

**Review by MaksimZhukov — APPROVED** [review]

**Pull request merged**
