### PR TITLE
Remove `restoreKeys` to clear cache after update

### PR DESCRIPTION
**Pull request by schuenadel**
**Description:**
Suggestion (like commented [here](https://github.com/actions/setup-java/issues/269#issuecomment-1012237641)) to remove fallback hash key to avoid keeping dependencies "forever". Start with a completely clean cache whenever **any** dependency changes. 

**Related issue:**
https://github.com/actions/setup-java/issues/269

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Comment by dmitry-shibanov** [comment]
Hello @schuenadel. Could you please sync with the main branch ?

**Comment by schuenadel** [comment]
@dmitry-shibanov done ✅

**Comment by paramaggarwal** [comment]
This is a bad change, this effectively makes caching useless when the linked file like `pom.xml` has even a tiny change.

**Comment by thomasmey** [comment]
Yes, setup-java should use a per build system strategy for setting the restore-keys, for maven build system this change is really bad

**Pull request merged**
