### PR TITLE
Prints error message encountered in cleanup-java

### PR DESCRIPTION
**Pull request by bbranan**
**Description:**
Updates the failure message in cleanup-java to include details of the error encountered.

**Related issue:**
https://github.com/actions/setup-java/issues/200

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Comment by dmitry-shibanov** [comment]
Hello @bbranan. Thank you for your pull request. Could you please run `npm run build` to regenerate dist directory?

**Comment by dmitry-shibanov** [comment]
Hello @bbranan. Could you please try to run `npm ci` or switch to node 12 with `npm 6.*` to revert changes in package-lock.json

**Comment by bbranan** [comment]
@dmitry-shibanov I could, but it seems that we're going around in circles for a really minor change. It may be easier for you to cherry pick my initial change and build it in your environment so that it matches the expected project setup. I'd be happy to either give you write access to my repo or close this PR to let you create another with the same initial commit.

**Comment by dmitry-shibanov** [comment]
Hello @bbranan. Pull request with adding error message is merged, that is why I'm closing your pull request.

**Review by KBPROPROMOTIONS — COMMENTED** [review]
?

**Pull request closed without merging**
